# Generated by Django 4.2.11 on 2024-03-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(to='homepages.product_category'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
