# Generated by Django 4.2.11 on 2024-03-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0002_alter_product_options_alter_discount_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='product_category',
            options={'verbose_name_plural': 'Product_categories'},
        ),
        migrations.AlterModelOptions(
            name='product_inventory',
            options={'verbose_name_plural': 'Product inventories'},
        ),
    ]
