# Generated by Django 4.2.11 on 2024-03-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0003_alter_product_image_alter_product_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='product_category',
            name='products',
            field=models.ManyToManyField(to='homepages.product'),
        ),
    ]
