# Generated by Django 4.2.11 on 2024-03-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0003_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={},
        ),
    ]
