# Generated by Django 4.2.11 on 2024-03-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0004_rename_product_category_product_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='products',
        ),
    ]
