# Generated by Django 4.2.11 on 2024-03-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0005_remove_product_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepages.product'),
        ),
    ]
