# Generated by Django 4.2.11 on 2024-03-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(verbose_name=django.db.models.deletion.SET_NULL),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(verbose_name=django.db.models.deletion.SET_NULL),
        ),
    ]
