# Generated by Django 4.2.11 on 2024-03-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0011_remove_product_sku_alter_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(verbose_name=0),
        ),
    ]
