# Generated by Django 4.2.11 on 2024-03-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0013_alter_product_deleted_at_alter_product_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='homepages/static/dist/img'),
        ),
    ]
