# Generated by Django 4.2.11 on 2024-03-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0015_alter_discount_deleted_at_alter_discount_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='desc',
        ),
    ]
