# Generated by Django 4.2.11 on 2024-03-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0016_remove_product_category_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='desc',
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepages.product'),
        ),
    ]
