# Generated by Django 4.2.11 on 2024-03-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0017_remove_discount_desc_alter_discount_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='name',
            new_name='connect',
        ),
    ]
