# Generated by Django 4.2.11 on 2024-03-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0018_rename_name_discount_connect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='connect',
            new_name='product_name',
        ),
    ]
