# Generated by Django 4.2.11 on 2024-03-05 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0021_product_inventory_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepages.product'),
        ),
    ]
