# Generated by Django 4.2.11 on 2024-03-05 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0022_alter_discount_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepages.product_category'),
            preserve_default=False,
        ),
    ]
