# Generated by Django 4.2.11 on 2024-03-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0023_product_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ManyToManyField(to='homepages.product_category'),
        ),
    ]
